name = "MutableNamedTuples"
uuid = "af6c499f-54b4-48cc-bbd2-094bba7533c7"
authors = ["MasonProtter <mason.protter@icloud.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]